### ISSUE TITLE
dubbo消费端调用接口完成后，jvm没有退出

### ISSUE THREAD

**Issue by simonaries** [apache/dubbo-awesome#112]
![image](https://github.com/apache/dubbo-awesome/assets/42372497/dc83d447-48b7-4821-a31f-8cc563d002b8)

如图，通过JProfiler发现还有dubbo的线程在等待，但是奇怪的是我再另外一台电脑上运行相同的代码时，不会出现这样的问题。

**Comment by AlbumenJ** [comment]
看一下这些线程的状态，如果是守护线程是不会阻塞 jvm 退出的

**Comment by AlbumenJ** [comment]
Duplicated with https://github.com/apache/dubbo/issues/12541
