### ISSUE TITLE
【Dubbo3.0-Docs】高级特性和用法——其他——Kubernetes 生命周期探针 文档缺失

### ISSUE THREAD

**Issue by CrazyHZM** [apache/dubbo-awesome#65]
内容分以下四部分来介绍：

- 特性说明
- 使用场景
- 使用方式
- 注意事项
原文文档：https://dubbo.apache.org/zh/docs/references/lifecycle/

**Comment by mfordjody** [comment]
assign

**Comment by chickenlj** [comment]
参考 https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-kubernetes

**Comment by CrazyHZM** [comment]
Solved by https://github.com/apache/dubbo-website/pull/1101
