### ISSUE TITLE
10th June 2022 : Dubbo Weekly Meeting

### ISSUE THREAD

**Issue by CrazyHZM** [apache/dubbo-awesome#71]
Time: 20:30
Online Dingding meeting room: 273 969 65845 (check the picture blow for how to join)

# Agenda
1.  https://github.com/apache/dubbo/issues/10077
2. Discuss version issues of the `dubbo-compiler` module and whether it is a standalone project.
3. Dubbo Mesh

**Comment by chickenlj** [comment]
![image](https://user-images.githubusercontent.com/18097545/173064098-1365a8f0-eca0-4786-9dfd-4a3fbef5f29c.png)
